-- Generated by running `todo.dart`

CREATE TABLE "users" (
  "id" serial,
  "username" varchar(32) UNIQUE,
  "password" varchar,
  "account_confirmed" serial
);
CREATE TABLE "todos" (
  "id" serial,
  "user_id" int REFERENCES "user"("id") ON DELETE CASCADE,
  "text" varchar,
  "completed" serial
);
